indydroid/indydroid/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'indydroid.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^puzzles/', include('puzzles.urls', namespace="puzzles")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
)

puzzles/puzzles/urls.py
from django.conf.urls import patterns, url

from puzzles import views

urlpatterns = patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^(?P<puzzle_display_id>\d+)/$', views.detail, name='detail'),
        url(r'^(?P<puzzle_display_id>\d+)/submit/$', views.submit, name='submit'),
        url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
)

puzzles/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Puzzle(models.Model):
    name = models.CharField(max_length=2000)
    display_id = models.IntegerField()
    active = models.BooleanField()
    solved = models.BooleanField()
    statement = models.CharField(max_length=2000)  # link for puzzle pdf
                                                   # consider a FileField?
    sol = models.CharField(max_length=2000)
    next_puzzle = models.ForeignKey('self', null=True, blank=True)

    team = models.CharField(max_length=2000, null=True, blank=True)

    search_fields = ['name', 'sol']

    def __unicode__(self):
        return self.name + ' | ' + self.team

class Submission(models.Model):
    puzzle = models.ForeignKey(Puzzle)
    answer = models.CharField(max_length=2000)
    timestamp = models.DateTimeField('time submitted')

    def __unicode__(self):
       return self.answer

    class Meta:
        get_latest_by = 'timestamp'

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    # optional, just for ease of querying. should match user.username
    name = models.CharField(max_length=2000, null=True, blank=True)

    # many-to-many to allow all team members to access the same puzzles
    puzzles = models.ManyToManyField(Puzzle, null=True, blank=True)
    team = models.CharField(max_length=2000, null=True, blank=True)

    def __unicode__(self):
        return self.user.username

puzzles/puzzles/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Puzzle(models.Model):
    name = models.CharField(max_length=2000)
    display_id = models.IntegerField()
    active = models.BooleanField()
    solved = models.BooleanField()
    statement = models.CharField(max_length=2000)  # link for puzzle pdf
                                                   # consider a FileField?
    sol = models.CharField(max_length=2000)
    next_puzzle = models.ForeignKey('self', null=True, blank=True)

    team = models.CharField(max_length=2000, null=True, blank=True)

    search_fields = ['name', 'sol']

    def __unicode__(self):
        return self.name + '|' + self.team + '|' + str(self.display_id)

class Submission(models.Model):
    puzzle = models.ForeignKey(Puzzle)
    answer = models.CharField(max_length=2000)
    timestamp = models.DateTimeField('time submitted')

    def __unicode__(self):
       return self.answer

    class Meta:
        get_latest_by = 'timestamp'

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    # optional, just for ease of querying. should match user.username
    name = models.CharField(max_length=2000, null=True, blank=True)

    # many-to-many to allow all team members to access the same puzzles
    puzzles = models.ManyToManyField(Puzzle, null=True, blank=True)
    team = models.CharField(max_length=2000, null=True, blank=True)

    def __unicode__(self):
        return self.user.username

puzzles/puzzles/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from django.utils import timezone

from puzzles.models import Puzzle, Submission

# Create your views here.
def user_login(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            print 'Authenticated user', user
            login(request, user)
            return HttpResponseRedirect('/puzzles/')
        else:
            print 'Received bad login from user', username
            # somehow mark bad login details
            return HttpResponseRedirect('/login/')
    else:
        return render(request, 'puzzles/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/puzzles/')

def intro(request):
    template = loader.get_template('/intro.html')
    context = RequestContext(request, {})
    return HttpResponse(template.render(context))

def index(request):
    if request.user.is_authenticated():
        active_puzzles = request.user.get_profile().puzzles.filter(active=True)
    else:
        active_puzzles = []
    template = loader.get_template('puzzles/index.html')
    context = RequestContext(request, {
        'active_puzzles': active_puzzles,
    })
    return HttpResponse(template.render(context))

@login_required
def detail(request, puzzle_display_id):
    try:
        profile = request.user.get_profile()
        p = profile.puzzles.get(display_id=puzzle_display_id)
    except Puzzle.DoesNotExist:
        raise Http404
    if not p.active:
        raise Http404
    return render(request, 'puzzles/detail.html', {'puzzle': p})

@login_required
def submit(request, puzzle_display_id):
    profile = request.user.get_profile()
    print puzzle_display_id
    print profile.puzzles.all()
    p = profile.puzzles.get(display_id=puzzle_display_id)
    try:
        submission = request.POST['submission']
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the puzzle submission form.
        return render(request, 'puzzles/detail.html', {'puzzle': p})
    else:
        p.submission_set.create(answer=submission, timestamp=timezone.now())
        # if correct, activate the next puzzle and get rid of the submit form
        if submission == p.sol:
            if p.next_puzzle:
                p.next_puzzle.active = True
                p.next_puzzle.save()
            p.solved = True
            p.save()
            return HttpResponseRedirect(reverse('puzzles:detail',
                args=(p.display_id,)))
        # if incorrect, redirect to the submit form and display that was wrong
        else:
            p.save()
            # implement messages to report wrong submission
            return HttpResponseRedirect(reverse('puzzles:detail',
                args=(p.display_id,)))

puzzles/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
from django.utils import timezone

from puzzles.models import Puzzle, Submission

# Create your views here.
def user_login(request):
    context = RequestContext(request)

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user:
            print 'Authenticated user', user
            login(request, user)
            return HttpResponseRedirect('/puzzles/')
        else:
            print 'Received bad login from user', username
            # somehow mark bad login details
            return HttpResponseRedirect('/puzzles/login')
    else:
        return render(request, 'puzzles/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/puzzles/')

def index(request):
    if request.user.is_authenticated():
        active_puzzles = request.user.get_profile().puzzles.filter(active=True)
    else:
        active_puzzles = []
    template = loader.get_template('puzzles/index.html')
    context = RequestContext(request, {
        'active_puzzles': active_puzzles,
    })
    return HttpResponse(template.render(context))

@login_required
def detail(request, puzzle_display_id):
    try:
        profile = request.user.get_profile()
        p = profile.puzzles.get(display_id=puzzle_display_id)
    except Puzzle.DoesNotExist:
        raise Http404
    if not p.active:
        raise Http404
    return render(request, 'puzzles/detail.html', {'puzzle': p})

@login_required
def submit(request, puzzle_display_id):
    profile = request.user.get_profile()
    p = profile.puzzles.get(display_id=puzzle_display_id)
    try:
        submission = request.POST['submission']
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the puzzle submission form.
        return render(request, 'puzzles/detail.html', {'puzzle': p})
    else:
        p.submission_set.create(answer=submission, timestamp=timezone.now())
        # if correct, activate the next puzzle and get rid of the submit form
        if submission == p.sol:
            if p.next_puzzle:
                p.next_puzzle.active = True
                p.next_puzzle.save()
            p.solved = True
            p.save()
            return HttpResponseRedirect(reverse('puzzles:detail', args=(p.id,)))
        # if incorrect, redirect to the submit form and display that was wrong
        else:
            p.save()
            # implement messages to report wrong submission
            return HttpResponseRedirect(reverse('puzzles:detail', args=(p.id,)))

puzzles/puzzles/templates/puzzles/detail.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'puzzles/style.css' %}" />

<div class="logout"><a href="/puzzles/logout/">Logout</a></div>

<header class="main-header" role="banner">
    <img src="/static/puzzles/images/indiana-logo.png" alt="Indiana Droid and the Holy Grail"/>
</header>

<h1><a href={{ puzzle.statement }} target="_blank">{{ puzzle.name }}</a></h1>

{% if puzzle.solved %}
<p>{{ puzzle.sol }}</p>
{% else %}
<form action="{% url 'puzzles:submit' puzzle.display_id %}" method="post">
{% csrf_token %}
<input type="text" name="submission" /><br />
<input type="submit" value="Submit" />
</form>
{% endif %}

<a href="/puzzles/">&#8592; Back to puzzles</a><br /><br />

puzzles/puzzles/templates/puzzles/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'puzzles/style.css' %}" />

{% if user.is_authenticated %}
<div class="logout"><a href="/puzzles/logout/">Logout</a></div>
{% endif %}

<header class="main-header" role="banner">
    <img src="/static/puzzles/images/indiana-logo.png" alt="Indiana Droid and the Holy Grail"/>
</header>

{% if user.is_authenticated %}
<h1>WELCOME, {{ user.get_profile.team }}!</h1>

<p>Indiana Droid needs your help. Tackle the puzzles below:</p>
{% if active_puzzles %}
    <ul>
    {% for puzzle in active_puzzles %}
    <li><a href="{% url 'puzzles:detail' puzzle.display_id %}">{{ puzzle.name }}</a>
    {% if puzzle.solved %} [SOLVED]{% endif %}
    </li>
    {% endfor %}
    </ul>
{% else %}
    <p>No puzzles are active.</p>
{% endif %}

{% else %}
<h1>WELCOME, ADVENTURER.</h1>
<p>After the [spoiler alert!] loss of the Holy Grail during Indiana Jones's escapades in the Last Crusade, [/spoiler alert!] Indiana Droid has heard rumors of the Holy Grail's resurface. Following clues and tips from his informants has led him to believe that it lies near a town hidden deep within the Amazon.
<br /><br />
It might involve deadly traps and government conspiracies, but Indy will find a way to reclaim the Grail, especially if you've got his back. Soon it'll be back in Goog-- in a museum, where it rightfully belongs.
<br /><br />
Will YOU be the one to find the Holy Grail first?
</p>
<a href="/puzzles/login/">Login</a>
<br />
{% endif %}

puzzles/puzzles/templates/puzzles/login.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'puzzles/style.css' %}" />

<header class="main-header" role="banner">
    <img src="/static/puzzles/images/indiana-logo.png" alt="Indiana Droid and the Holy Grail"/>
</header>

{% if user.is_authenticated %}
<p>You're already logged in. Did you mean to log out?</p>

<a href="/puzzles/">&#8592; Back to puzzles</a>
{% else %}
<h1>LOGIN</h1>
<form id="login_form" method="post" action="/puzzles/login/">
    {% csrf_token %}
    Username: <input type="text" name="username" value="" size="50" /><br />
    Password: <input type="password" name="password" value="" size="50" /><br />
    <input type="submit" value="Login" />
</form>

<a href="/puzzles/">&#8592; Back to puzzles</a>
{% endif %}